#!/usr/bin/env bash

APM_BIN="/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/apm install"

$APM_BIN activate-power-mode
$APM_BIN busy-signal
$APM_BIN editorconfig
$APM_BIN file-icons
$APM_BIN git-blame
$APM_BIN git-time-machine
$APM_BIN hyperclick
$APM_BIN intentions
$APM_BIN language-babel
$APM_BIN linter
$APM_BIN linter-eslint
$APM_BIN linter-phpcs
$APM_BIN linter-ui-default
$APM_BIN minimap
$APM_BIN php-integrator-annotations
$APM_BIN php-integrator-autocomplete-plus
$APM_BIN php-integrator-base
$APM_BIN php-integrator-call-tips
$APM_BIN php-integrator-linter
$APM_BIN php-integrator-navigation
$APM_BIN php-integrator-refactoring
$APM_BIN php-integrator-symbol-viewer
$APM_BIN php-integrator-tooltips
$APM_BIN project-manager
